[SPECTROGRAM]
fft_size = 512
step_size = 64
freq_cutoffs = [ 500, 10000,]
thresh = 6.25
transform_type = "log_spect"

[TRAIN]
normalize_spectrograms = "Yes"
num_epochs = 50
val_error_step = 1
checkpoint_step = 1
save_only_single_checkpoint_file = true
patience = 4
replicates = 4
models = "TweetyNet"
root_results_dir = "~/Documents/data/BFSongRepository/vak/or60yw70"
batch_size = 11

[PREP]
labelset = "iabcdefg"
data_dir = "~/Documents/data/BFSongRepository/or60yw70/092812/train_subset_480s"
output_dir = "~/Documents/data/BFSongRepository/vak/or60yw70"
audio_format = "cbin"
annot_format = "notmat"
test_dur = 0
train_dur = 480
val_dur = 80

[DATALOADER]
window_size = 88

[TweetyNet.optimizer]
lr = 0.001

